# constant


In [6]:
#import
import tensorflow as tf


In [7]:
tf.compat.v1.disable_eager_execution() # need to disable eager in TF2. x  #sessions


In [4]:
a=tf.constant(3)
b=tf.constant(3,tf.float32)
c=tf.constant([2,5,6,9,6])
d=tf.constant([  [2,5,6],
              	[8,5,8],
              	[8,8,1]])
e=tf.constant('My python tensorflow')

In [5]:
with tf.compat.v1.Session() as sess:
    print(sess.run(a))
    print(sess.run(b))
    print(sess.run(c))
    print(sess.run(d))
    print(sess.run(e))

3
3.0
[2 5 6 9 6]
[[2 5 6]
 [8 5 8]
 [8 8 1]]
b'My python tensorflow'
