# operations

In [40]:
#import
import tensorflow as tf
from tensorflow.compat.v1 import Session
import numpy as np


In [15]:
tf.compat.v1.disable_eager_execution() # need to disable eager in TF2. x  #sessions


In [16]:
s1= tf.constant('hi ')
s2=tf.constant("people")

s3=tf.add(s1,s2)
sess=  tf.compat.v1.Session() 
print(sess.run(s3))

b'hi people'


In [18]:
s1=tf.constant(20)
s2=tf.constant(30)

s3=tf.multiply(s1,s2)
sess=Session()
print(sess.run(s3))

600


In [19]:
s1=tf.constant(20)
s2=tf.constant(30)

s3=tf.subtract(s1,s2)
sess=Session()
print(sess.run(s3))

-10


In [20]:
s1=tf.constant(20)
s2=tf.constant(30)

s3=tf.divide(s1,s2)
sess=Session()
print(sess.run(s3))

0.6666666666666666


In [22]:
s1=tf.constant(2)
s2=tf.constant(3)

s3=tf.pow(s1,s2)
sess=Session()
print(sess.run(s3))

8


In [24]:
s1=tf.constant([5,6,7,8])
s2=tf.constant(30)

s3=tf.add(s1,s2)
sess=Session()
print(sess.run(s3))

[35 36 37 38]


In [28]:
s1=tf.constant(2)
s2=tf.constant(list(range(0,11,2)))

s3=tf.pow(s1,s2)
sess=Session()
print(sess.run(s3))

[   1    4   16   64  256 1024]


In [29]:
s1=tf.constant([5,6,7,8])
s2=tf.constant([1,2,3,4])

s3=tf.add(s1,s2)
sess=Session()
print(sess.run(s3))

[ 6  8 10 12]


In [32]:

matrix1=tf.constant( [   [5.,3.]  ] )
matrix2=tf.constant( [   [2.],
                     	 [2.]] )

proudct =tf.matmul(matrix1 ,matrix2)
with Session() as sess:
    print(sess.run(proudct))

[[16.]]


In [42]:
matrix1= tf.constant(np.random.randint(8,size=(2,4)))
matrix2=tf.compat.v1.matrix_transpose(matrix1)

with Session() as sess:
    print(sess.run(matrix2))

[[5 6]
 [2 6]
 [4 1]
 [4 7]]
