# Varibale

In [18]:
#import
import tensorflow as tf
#from tensorflow.compat import v1 as tff

In [6]:
tf.compat.v1.disable_eager_execution() # need to disable eager in TF2. x  #sessions
tf.compat.v1.global_variables_initializer()    #Varibale

<tf.Operation 'init' type=NoOp>

In [7]:
a=tf.Variable(3)
b=tf.Variable(3,tf.float32)
c=tf.Variable([2,5,6,9,6])
d=tf.Variable([  [2,5,6],
              	[8,5,8],
              	[8,8,1]])
e=tf.Variable('My python tensorflow')

In [8]:
with tf.compat.v1.Session() as sess:
    sess.run(tf.compat.v1.global_variables_initializer())
    print(sess.run(a))
    print(sess.run(b))
    print(sess.run(c))
    print(sess.run(d))
    print(sess.run(e))

3
3
[2 5 6 9 6]
[[2 5 6]
 [8 5 8]
 [8 8 1]]
b'My python tensorflow'


In [9]:
price= tf.Variable(20)
sess = tf.compat.v1.Session()
init =tf.compat.v1.global_variables_initializer() 
sess.run(init)
print("original price is :" , sess.run(price))

original price is : 20


In [10]:
# Modify the value of the variable
price =tf.Variable(30)
sess.run(tf.compat.v1.global_variables_initializer())
print('the price is :',sess.run(price))

price=tf.Variable(40)
sess.run(tf.compat.v1.global_variables_initializer())
print('the price is :',sess.run(price))

price=tf.Variable(50)
sess.run(tf.compat.v1.global_variables_initializer())
print('the price is :',sess.run(price))


price=tf.Variable(50)
sess.run(tf.compat.v1.global_variables_initializer())
print('the price is :',sess.run(price))

the price is : 30
the price is : 40
the price is : 50
the price is : 50


In [11]:
price=tf.compat.v1.assign(price,50)

In [12]:
#from tensorflow.compat import v1 

In [13]:
price=tf.compat.v1.assign(price,55)
print("new price is :" )
sess.run(price)

new price is :


55

In [14]:
sess.run(price)

55

In [17]:
for i in range(100):
    price=tf.compat.v1.assign(price , price+10)
    print(sess.run(price))

215
225
235
245
255
265
275
285
295
305
315
325
335
345
355
365
375
385
395
405
415
425
435
445
455
465
475
485
495
505
515
525
535
545
555
565
575
585
595
605
615
625
635
645
655
665
675
685
695
705
715
725
735
745
755
765
775
785
795
805
815
825
835
845
855
865
875
885
895
905
915
925
935
945
955
965
975
985
995
1005
1015
1025
1035
1045
1055
1065
1075
1085
1095
1105
1115
1125
1135
1145
1155
1165
1175
1185
1195
1205
